### ISSUE TITLE
Manifold optimization embedding

### ISSUE THREAD

**Issue by luca-morreale** [patr-schm/TinyAD-Examples#2]
Hi Patrick,
amazing work! 

I am trying to replicate the manifold example from scratch, i.e., without the embedding given.
What algorithm/energy did you use to compute the initial embedding for the giraffe?
Eventually, I am going to do this also with other meshes.

Thank you very much!

Luca

**Comment by patr-schm** [comment]
Hi Luca,

thanks! I used `multi_res_sphere_embedding(..)` from https://github.com/patr-schm/surface-maps-via-adaptive-triangulations/blob/main/src/SurfaceMaps/MultiRes/MultiResSphereEmbedding.hh.

The function decimates a genus-0 mesh to a tetrahedron, embeds it on the sphere, and then bijectively re-inserts all vertices (one independent set at a time). This is interleaved with a few iterations of global optimization. By tuning the settings in https://github.com/patr-schm/surface-maps-via-adaptive-triangulations/blob/main/src/SurfaceMaps/MultiRes/MultiResSphereEmbeddingSettings.hh you can balance speed, quality, and robustness.

The energy is a sum of angle and area distortion similar to https://www.graphics.rwth-aachen.de/media/papers/309/s2020-inter-surface-maps-low.pdf Sec 6.6.

Hope this helps

Best
Patrick

Edit: I realized that this is not how I computed the embedding in that example, but it's what I'd recommend to do
